// <auto-generated />
using System;
using MemeSearcher.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemeSearcher.Infrastructure.Database.Migrations
{
    [DbContext(typeof(MemeSearcherDbContext))]
    [Migration("20260824015847_AddMediaLastRealignAttemptAt")]
    partial class AddMediaLastRealignAttemptAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("MemeSearcher.Core.Models.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelectedForSearch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastRealignAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaFilePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptionComputeType")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptionDevice")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptionModel")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("Path");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("MemeSearcher.Core.Models.Phone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alphabet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("EndSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("StartSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WordId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WordId", "Sequence");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("MemeSearcher.Core.Models.PhoneNGramPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NGram")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StreamPosition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaId", "NGram", "StreamPosition")
                        .IsUnique();

                    b.ToTable("PhoneNGramPostings");
                });

            modelBuilder.Entity("MemeSearcher.Core.Models.SearchHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComposite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResultCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScopeDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SearchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedMediaIdsCsv")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SearchedAt");

                    b.ToTable("SearchHistory");
                });

            modelBuilder.Entity("MemeSearcher.Core.Models.Segment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("EndSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Ipa")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedText")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhonemeSequence")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("StartSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TranscriptId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TranscriptId", "Sequence");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("MemeSearcher.Core.Models.Transcript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.ToTable("Transcripts");
                });

            modelBuilder.Entity("MemeSearcher.Core.Models.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("EndSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Ipa")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedText")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhonemeAlphabet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhonemeSequence")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SegmentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("StartSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SegmentId", "Sequence");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("MemeSearcher.Core.Models.Phone", b =>
                {
                    b.HasOne("MemeSearcher.Core.Models.Word", null)
                        .WithMany("Phones")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MemeSearcher.Core.Models.PhoneNGramPosting", b =>
                {
                    b.HasOne("MemeSearcher.Core.Models.Media", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MemeSearcher.Core.Models.Segment", b =>
                {
                    b.HasOne("MemeSearcher.Core.Models.Transcript", null)
                        .WithMany("Segments")
                        .HasForeignKey("TranscriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MemeSearcher.Core.Models.Transcript", b =>
                {
                    b.HasOne("MemeSearcher.Core.Models.Media", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MemeSearcher.Core.Models.Word", b =>
                {
                    b.HasOne("MemeSearcher.Core.Models.Segment", null)
                        .WithMany("Words")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MemeSearcher.Core.Models.Segment", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("MemeSearcher.Core.Models.Transcript", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("MemeSearcher.Core.Models.Word", b =>
                {
                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
